// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektTemperatur;

namespace ProjektTemperatur.Migrations
{
    [DbContext(typeof(ProjektarbeteContext))]
    partial class ProjektarbeteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProjektTemperatur.Temperaturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("luftfuktighet")
                        .HasColumnType("int");

                    b.Property<string>("plats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("temp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Datavardes");
                });
#pragma warning restore 612, 618
        }
    }
}
